apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - ../../bases/cluster-issuer/

generators:
  - ./secret-generator.yaml

patches:
  - target:
      kind: ClusterIssuer
      name: letsencrypt-prod
    path: dns01-cloudflare.patch.yaml

  - target:
      kind: ClusterIssuer
      name: letsencrypt-staging
    path: dns01-cloudflare.patch.yaml