urlshortener:
  urlshortener:
    replicaCount: 1

    image:
      pullPolicy: Always
      tag: develop

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: short.av0.de
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: short-av0-de-tls
          hosts:
            - short.av0.de

    metrics:
      enabled: true

  apiServer:
    replicaCount: 1
    image:
      pullPolicy: Always
      tag: develop

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: api.short.av0.de
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: api-short-av0-de-tls
          hosts:
            - api.short.av0.de
    
    metrics:
      enabled: true