ingress-nginx:
  fullnameOverride: ingress-nginx
  controller:
    kind: Deployment
    watchIngressWithoutClass: true
    service:
      enabled: true
      externalTrafficPolicy: "Local"
      annotations:
        metallb.universe.tf/address-pool: tailscale-ips
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
