ingress-nginx:
  fullnameOverride: ingress-nginx
  controller:
    kind: DaemonSet
    watchIngressWithoutClass: true
    service:
      enabled: true
      externalTrafficPolicy: "Local"
      #healthCheckNodePort: 32596
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "av0.de."
    metrics:
      enabled: true
      serviceMonitor:
        #enabled: true
