ingress-nginx:
  fullnameOverride: ingress-nginx
  controller:
    extraArgs:
      enable-ssl-passthrough: ''
    kind: DaemonSet
    watchIngressWithoutClass: true
    service:
      enabled: true
      externalTrafficPolicy: "Local"
      healthCheckNodePort: 32596
      annotations:
        load-balancer.hetzner.cloud/location: "nbg1"
        load-balancer.hetzner.cloud/name: "cedi-dev-ingress-lb"
        load-balancer.hetzner.cloud/type: "lb11"
        load-balancer.hetzner.cloud/algorithm-type: "least_connections"
        load-balancer.hetzner.cloud/health-check-protocol: "http"
        load-balancer.hetzner.cloud/health-check-port: "32596"
        load-balancer.hetzner.cloud/disable-private-ingress: true
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
