apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentelemetry-operator-system

bases:
  - ../../bases/otel-collector-operator

patchesStrategicMerge:
  - delete-extra-namespace.patch.yaml