cert-manager:
  fullnameOverride: cert-manager
  global:
    leaderElection:
      namespace: cert-manager
  installCRDs: true
  prometheus:
    enabled: false
    servicemonitor:
      enabled: false
