apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-cluster-issuer
  namespace: argocd
spec:
  destination:
    namespace: cluster-issuer
    server: https://100.94.122.53:6443
  project: default
  source:
    path: kustomize/overlays/cluster-issuer
    repoURL: https://github.com/av0de/k8s-manifests.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
