apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: 'https://github.com/av0de/k8s-manifests.git'
    path: charts/ingress-nginx
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://100.124.74.37:6443'
    namespace: ingress-nginx
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
