apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: metallb-system
    server: 'https://100.94.122.53:6443'
  source:
    path: bin
    repoURL: 'https://github.com/metallb/metallb-operator.git'
    targetRevision: v0.12.0
  project: default
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  #  syncOptions:
  #    - CreateNamespace=true
