apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: metallb-system
    server: 'https://100.94.122.53:6443'
  source:
    path: charts/metallb
    repoURL: 'https://github.com/av0de/k8s-manifests.git'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
