apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-test-chart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: testing
    server: 'https://100.94.122.53:6443'
  project: default
  source:
    path: charts/test-chart
    repoURL: 'https://github.com/av0de/k8s-manifests.git'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - values.secret.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
