apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-test-deployment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://100.94.122.53:6443'
  project: default
  source:
    path: manifests/test-deployment
    repoURL: https://github.com/av0de/k8s-manifests.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
