apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-urlshortener
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: urlshortener
    server: 'https://100.124.74.37:6443'
  source:
    path: charts/urlshortener
    repoURL: 'https://github.com/cedi-dev/k8smanifests.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
